import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const tokens = JSON.parse(readFileSync(resolve(root, 'tokens/tokens.json'), 'utf8'));

const PREFIX = 'strata';

function deref(value) {
  if (typeof value !== 'string') return value;
  return value.replace(/\{([^}]+)\}/g, (_, path) => {
    const parts = path.split('.');
    let node = tokens;
    for (const p of parts) {
      node = node?.[p];
      if (node === undefined) throw new Error(`Unresolved token reference: {${path}}`);
    }
    const raw = node.$value ?? node;
    return deref(raw);
  });
}

function flattenPrimitives(obj, path = []) {
  const out = [];
  for (const [key, val] of Object.entries(obj)) {
    if (key.startsWith('$')) continue;
    if (val && typeof val === 'object' && '$value' in val) {
      out.push([[...path, key].join('-'), deref(val.$value)]);
    } else if (val && typeof val === 'object') {
      out.push(...flattenPrimitives(val, [...path, key]));
    }
  }
  return out;
}

const primitiveGroups = ['color', 'font', 'space', 'radius', 'border', 'duration', 'easing'];
const primitives = primitiveGroups.flatMap((g) => flattenPrimitives(tokens[g], [g]));

const semanticVars = (set) =>
  Object.entries(set).map(([name, value]) => [name, deref(value)]);

const cssBlock = (selector, vars, indent = '  ') =>
  `${selector} {\n${vars.map(([n, v]) => `${indent}--${PREFIX}-${n}: ${v};`).join('\n')}\n}`;

const css = [
  '/* Generated by scripts/build-tokens.mjs — do not edit. Source: tokens/tokens.json */',
  cssBlock(':root', [
    ...primitives,
    ...semanticVars(tokens.semantic.light),
  ]),
  cssBlock('[data-theme="dark"]', semanticVars(tokens.semantic.dark)),
  cssBlock('[data-variant="showcase"]', semanticVars(tokens.variants.showcase.light)),
  cssBlock(
    '[data-theme="dark"][data-variant="showcase"]',
    semanticVars(tokens.variants.showcase.dark)
  ),
  '',
].join('\n\n');

const genDir = resolve(root, 'src/generated');
mkdirSync(genDir, { recursive: true });
writeFileSync(resolve(genDir, 'tokens.css'), css);

const toObj = (pairs) => Object.fromEntries(pairs.map(([n, v]) => [n, v]));
const ts = [
  '/* Generated by scripts/build-tokens.mjs — do not edit. Source: tokens/tokens.json */',
  `export const primitives = ${JSON.stringify(toObj(primitives), null, 2)} as const;`,
  `export const light = ${JSON.stringify(toObj(semanticVars(tokens.semantic.light)), null, 2)} as const;`,
  `export const dark = ${JSON.stringify(toObj(semanticVars(tokens.semantic.dark)), null, 2)} as const;`,
  '',
].join('\n\n');
writeFileSync(resolve(genDir, 'tokens.ts'), ts);

console.log(`tokens: ${primitives.length} primitives, ${Object.keys(tokens.semantic.light).length} semantic (light), ${Object.keys(tokens.semantic.dark).length} semantic (dark)`);
